# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RpUE8YRQEvS0t5mOWEYCdv94JSCvRBk
"""

import networkx as nx
import matplotlib.pyplot as plt
import itertools
import random
from IPython.display import clear_output

# ======================
# Utility functions
# ======================

def target_edges(n, target):
    """Return all edge sets that form the target cycle C3, C4, or C5."""
    nodes = list(range(n))
    k = int(target[1])
    subgraphs = []
    for combo in itertools.combinations(nodes, k):
        cycle_edges = [(combo[i], combo[(i+1)%k]) for i in range(k)]
        subgraphs.append(set(tuple(sorted(e)) for e in cycle_edges))
    return subgraphs


def check_maker_win(maker_edges, target_subgraphs):
    """Check if Maker has completed any target subgraph."""
    maker_set = set(tuple(sorted(e)) for e in maker_edges)
    for sub in target_subgraphs:
        if sub.issubset(maker_set):
            return True
    return False


def draw_graph(G, maker_edges, breaker_edges, pos):
    """Draw the game graph with colored edges (non-blocking)."""
    plt.clf()
    nx.draw_networkx_nodes(G, pos, node_color="lightgrey", node_size=500)

    remaining_edges = [e for e in G.edges() if e not in maker_edges and e not in breaker_edges]
    nx.draw_networkx_edges(G, pos, edgelist=remaining_edges, edge_color="grey", style="dotted", width=1.5)
    nx.draw_networkx_edges(G, pos, edgelist=maker_edges, edge_color="red", width=2)
    nx.draw_networkx_edges(G, pos, edgelist=breaker_edges, edge_color="blue", width=2)
    nx.draw_networkx_labels(G, pos, font_color="black", font_size=12)
    plt.axis("off")
    plt.title("Maker (Red) vs Breaker (Blue)")
    plt.show(block=False)
    plt.pause(0.1)


# ======================
# Game Setup
# ======================

n = int(input("Enter number of nodes (n) for complete graph K_n: "))
q = int(input("Enter bias q (Breaker claims q edges per turn): "))
target_choice = input("Enter target subgraph (C3, C4, or C5): ").upper()

G = nx.complete_graph(n)
pos = nx.spring_layout(G, seed=42)

target_subgraphs = target_edges(n, target_choice)
maker_edges = []
breaker_edges = []
available_edges = list(G.edges())
random.shuffle(available_edges)

clear_output(wait=True)
print(f"Game started: Maker–Breaker on K{n} with bias q={q} and target={target_choice}\n")
draw_graph(G, maker_edges, breaker_edges, pos)

# ======================
# Gameplay Loop
# ======================

turn = 1
while available_edges:
    print(f"\n--- Turn {turn} ---")
    print(f"Available edges: {len(available_edges)}")

    # Maker move
    maker_move = input("Maker's turn — pick an edge (e.g., '0 1'): ")
    try:
        u, v = map(int, maker_move.strip().split())
        edge = tuple(sorted((u, v)))
        if edge not in available_edges:
            print("Invalid move! Edge not available.")
            continue
    except:
        print("Invalid input format.")
        continue

    maker_edges.append(edge)
    available_edges.remove(edge)
    draw_graph(G, maker_edges, breaker_edges, pos)

    # Check Maker win
    if check_maker_win(maker_edges, target_subgraphs):
        print("Maker wins by completing the target subgraph!")
        break

    # Breaker move(s)
    for i in range(q):
        if not available_edges:
            break
        breaker_move = input(f"Breaker move {i+1}/{q} — pick an edge (e.g., '0 2'): ")
        try:
            u, v = map(int, breaker_move.strip().split())
            edge = tuple(sorted((u, v)))
            if edge not in available_edges:
                print("Invalid move! Edge not available.")
                continue
        except:
            print("Invalid input format.")
            continue

        breaker_edges.append(edge)
        available_edges.remove(edge)
        draw_graph(G, maker_edges, breaker_edges, pos)

    turn += 1

    if not available_edges:
        print("All edges claimed. Game over.")
        break

# Final Results
print("\nFinal Board:")
draw_graph(G, maker_edges, breaker_edges, pos)

if not check_maker_win(maker_edges, target_subgraphs):
    print("Breaker wins! Maker failed to complete the target subgraph.")