# -*- coding: utf-8 -*-
"""sowa_srivastav_c4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USrXMsDjbTDnmX8jD-jeRk2ITV47chj_
"""

import math
import random
from itertools import combinations
from dataclasses import dataclass, field
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np

IITR_BLUE   = "#1f497d"
IITR_ORANGE = "#df802a"
BREAKER_RED = "#cc2222"
THREAT_GOLD = "#e0b020"

plt.rcParams["figure.dpi"] = 110

"""## 1. Helper functions"""

def edge(u, v):
    """Canonical undirected edge as a frozenset."""
    return frozenset({u, v})

def maker_degree(v, M):
    return sum(1 for e in M if v in e)

def neighbours(v, edges):
    return {u for e in edges if v in e for u in e if u != v}

def threats(e, M):
    """T_e = {{b1,b2} : b1 in N_M(a1), b2 in N_M(a2)} \\ {e}.
    Each threat, combined with e, closes a C_4 using existing Maker edges.
    """
    a1, a2 = tuple(e)
    N1, N2 = neighbours(a1, M), neighbours(a2, M)
    out = set()
    for b1 in N1:
        for b2 in N2:
            if b1 != b2:
                t = edge(b1, b2)
                if t != e:
                    out.add(t)
    return out

def contains_c4(M):
    """True iff M contains a 4-cycle (no chords required)."""
    adj = {}
    for e in M:
        u, v = tuple(e)
        adj.setdefault(u, set()).add(v)
        adj.setdefault(v, set()).add(u)
    nodes = list(adj.keys())
    for u, v in combinations(nodes, 2):
        common = adj[u] & adj[v]
        if len(common) >= 2:
            return True
    return False

def random_breaker(free, q, rng):
    pool = list(free)
    rng.shuffle(pool)
    return set(pool[:q])

def adversarial_breaker(free, M, q, must_block=None):
    """Greedy: prioritise edges in `must_block`, then edges with highest |T_e|."""
    picks = []
    if must_block:
        for t in must_block:
            if t in free and t not in picks:
                picks.append(t)
                if len(picks) == q:
                    return set(picks)
    scored = sorted(
        (e for e in free if e not in picks),
        key=lambda e: -len(threats(e, M))
    )
    for e in scored:
        picks.append(e)
        if len(picks) == q:
            break
    return set(picks)

@dataclass
class GameLog:
    n: int
    d: int
    q: int
    M: set = field(default_factory=set)
    B: set = field(default_factory=set)
    free: set = field(default_factory=set)
    history: list = field(default_factory=list)  # (round, who, edge, phase)
    X_at_end_of_phase1: set = field(default_factory=set)
    e_star: Optional[frozenset] = None
    threats_e_star: set = field(default_factory=set)
    closing_edge: Optional[frozenset] = None
    cycle: Optional[list] = None
    winner: str = "undecided"

def play_sowa_srivastav(n, q, d, breaker="adversarial", seed=0, verbose=False):
    """Run the full Sowa–Srivastav C_4 strategy and return a GameLog.

    Parameters
    ----------
    n         : number of vertices
    q         : Breaker's bias (edges per round)
    d         : target Maker-degree (= ceil(delta * n^(1/3)))
    breaker   : 'random' or 'adversarial'
    seed      : RNG seed for tie-breaking / random Breaker
    verbose   : print a round-by-round trace
    """
    rng = random.Random(seed)
    V = list(range(n))
    log = GameLog(n=n, d=d, q=q)
    log.free = {edge(u, v) for u, v in combinations(V, 2)}

    def breaker_move(must_block=None):
        if breaker == "random":
            return random_breaker(log.free, q, rng)
        return adversarial_breaker(log.free, log.M, q, must_block=must_block)

    # -------- Phase 1 --------
    rd = 0
    while True:
        candidates = [
            e for e in log.free
            if max(maker_degree(u, log.M) for u in e) < d
        ]
        if not candidates:
            break
        rng.shuffle(candidates)
        e = min(candidates,
                key=lambda e: sum(maker_degree(u, log.M) for u in e))
        rd += 1
        log.free.discard(e)
        log.M.add(e)
        log.history.append((rd, "M", e, "P1"))
        if verbose:
            print(f"Rd {rd:2d} | Maker plays {set(e)}  (P1)")
        # Breaker
        for b in breaker_move():
            log.free.discard(b)
            log.B.add(b)
            log.history.append((rd, "B", b, "P1"))
            if verbose:
                print(f"       Breaker plays {set(b)}")

    log.X_at_end_of_phase1 = {v for v in V if maker_degree(v, log.M) >= d}
    if verbose:
        print(f"\nPhase 1 done in {rd} Maker rounds.")
        print(f"X = {sorted(log.X_at_end_of_phase1)}, |X| = {len(log.X_at_end_of_phase1)}")

    # -------- Phase 2: find active dangerous --------
    X = log.X_at_end_of_phase1
    e_star = None
    T_star = None
    candidates = [e for e in log.free if all(u in X for u in e)]
    candidates.sort(key=lambda e: -len(threats(e, log.M) - log.B))
    for e in candidates:
        T_e = threats(e, log.M)
        if len(T_e - log.B) > q:
            e_star = e
            T_star = T_e
            break
    if e_star is None:
        log.winner = "Breaker (no active dangerous edge)"
        if verbose:
            print("No active dangerous edge — Breaker wins or strategy fails for this n,q.")
        return log
    log.e_star = e_star
    log.threats_e_star = T_star
    rd += 1
    log.free.discard(e_star)
    log.M.add(e_star)
    log.history.append((rd, "M", e_star, "P2"))
    if verbose:
        free_threats = T_star - log.B
        print(f"\nRd {rd:2d} | Maker plays e* = {set(e_star)}  (P2)")
        print(f"       |T_e*| = {len(T_star)}, free threats = {len(free_threats)} > q={q}")
    # Breaker
    for b in breaker_move(must_block=T_star - log.B):
        log.free.discard(b)
        log.B.add(b)
        log.history.append((rd, "B", b, "P2"))
        if verbose:
            print(f"       Breaker plays {set(b)}")

    # -------- Phase 3: close --------
    survivors = T_star - log.B
    if not survivors:
        log.winner = "Breaker (Lemma 7(vi) violated — small n?)"
        return log
    closer = next(iter(survivors))
    rd += 1
    log.free.discard(closer)
    log.M.add(closer)
    log.closing_edge = closer
    log.history.append((rd, "M", closer, "P3"))
    # Reconstruct cycle order: a1 - b1 - b2 - a2 - a1
    a1, a2 = tuple(e_star)
    b1, b2 = tuple(closer)
    if b1 in neighbours(a1, log.M) and b2 in neighbours(a2, log.M):
        log.cycle = [a1, b1, b2, a2]
    else:
        log.cycle = [a1, b2, b1, a2]
    log.winner = "Maker"
    if verbose:
        print(f"\nRd {rd:2d} | Maker plays closer {set(closer)}  (P3)")
        print(f"       C_4: {' → '.join(map(str, log.cycle + [log.cycle[0]]))}")
        print(f"\nWinner: Maker ✓")
    return log

def vertex_positions(n, radius=1.0):
    return {i: (radius*np.cos(2*np.pi*i/n + np.pi/2),
                radius*np.sin(2*np.pi*i/n + np.pi/2))
            for i in range(n)}

def draw_state(log, ax=None, title=None,
               show_threats=False, highlight_cycle=False,
               highlight_e_star=False):
    if ax is None:
        fig, ax = plt.subplots(figsize=(6, 6))
    pos = vertex_positions(log.n)

    # C_4 halo (behind everything)
    if highlight_cycle and log.cycle:
        cyc = log.cycle + [log.cycle[0]]
        for u, v in zip(cyc, cyc[1:]):
            ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                    color=IITR_ORANGE, linewidth=14, alpha=0.25, zorder=0,
                    solid_capstyle="round")

    # Live threats (dotted gold)
    if show_threats and log.e_star is not None:
        free_threats = log.threats_e_star - log.B
        for t in free_threats:
            u, v = tuple(t)
            ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                    color=THREAT_GOLD, linewidth=2.2, linestyle=":", zorder=1)

    # Breaker edges (dashed red)
    for e in log.B:
        u, v = tuple(e)
        ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                color=BREAKER_RED, linewidth=1.4, linestyle="--",
                alpha=0.85, zorder=2)

    # Maker edges (solid blue, or orange for closer/e*)
    closing = {log.e_star, log.closing_edge} - {None}
    for e in log.M:
        u, v = tuple(e)
        if highlight_e_star and e in closing:
            ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                    color=IITR_ORANGE, linewidth=3.2, zorder=3)
        else:
            ax.plot([pos[u][0], pos[v][0]], [pos[u][1], pos[v][1]],
                    color=IITR_BLUE, linewidth=2.2, zorder=3)

    # Vertices
    for i, (x, y) in pos.items():
        ax.scatter([x], [y], s=300, color=IITR_BLUE, zorder=4)
        ax.text(x*1.18, y*1.18, str(i), ha="center", va="center",
                fontsize=12, fontweight="bold", color="black")

    ax.set_aspect("equal")
    ax.set_xlim(-1.35, 1.35); ax.set_ylim(-1.35, 1.35)
    ax.axis("off")
    if title:
        ax.set_title(title, fontsize=13, color=IITR_BLUE, fontweight="bold")
    return ax

def draw_three_phases(log, figsize=(16, 5.5)):
    """Side-by-side panels showing the state after each phase."""
    fig, axes = plt.subplots(1, 3, figsize=figsize)
    # Snapshot after Phase 1: build a synthetic log with only P1 edges
    p1_log = GameLog(n=log.n, d=log.d, q=log.q)
    for (rd, who, e, phase) in log.history:
        if phase == "P1":
            (p1_log.M if who == "M" else p1_log.B).add(e)
    draw_state(p1_log, ax=axes[0], title="After Phase 1 (d-degree)")

    # After Phase 2 (Maker plays e*)
    p2_log = GameLog(n=log.n, d=log.d, q=log.q)
    for (rd, who, e, phase) in log.history:
        if phase in ("P1", "P2"):
            (p2_log.M if who == "M" else p2_log.B).add(e)
    p2_log.e_star = log.e_star
    p2_log.threats_e_star = log.threats_e_star
    draw_state(p2_log, ax=axes[1], title="After Phase 2 (play $e^*$)",
               show_threats=True, highlight_e_star=True)

    # After Phase 3 (cycle closed)
    draw_state(log, ax=axes[2], title="After Phase 3 ($C_4$ closed)",
               highlight_cycle=True, highlight_e_star=True)
    plt.tight_layout()
    return fig

"""## 5. Quick demo: the $K_6$ worked example

Parameters: $n = 6$, target degree $d = 2$, bias $q = 1$, adversarial Breaker, seed = 0.
"""

log = play_sowa_srivastav(n=6, q=1, d=2, breaker="adversarial", seed=0, verbose=True)

fig = draw_three_phases(log)
plt.show()

"""## 6. Interactive demo

Drag the sliders to play the strategy on different game sizes and biases.

**Note.** For the Sowa–Srivastav proof to apply, you need $q < 0.16\,n^{2/3}$. At small $n$ the constants don't bind, but the algorithm still fires phase-by-phase; if Phase 2 finds no active dangerous edge, the cell prints "Breaker wins".
"""

from ipywidgets import interact, IntSlider, Dropdown, IntText, Checkbox
from IPython.display import display, Markdown

def _show(n, q, d, breaker, seed, verbose):
    log = play_sowa_srivastav(n=n, q=q, d=d, breaker=breaker,
                              seed=seed, verbose=verbose)
    c = q / n**(2/3)
    delta = d / n**(1/3)
    beta = len(log.X_at_end_of_phase1) / n
    md = (f"**Result:** {log.winner}\u2003 "
          f"**Implied parameters:** "
          f"$c \\approx {c:.3f}$, "
          f"$\\delta \\approx {delta:.3f}$, "
          f"$\\beta \\approx {beta:.3f}$")
    display(Markdown(md))
    fig = draw_three_phases(log)
    plt.show()

interact(
    _show,
    n=IntSlider(min=4, max=14, step=1, value=6, description="n"),
    q=IntSlider(min=1, max=6, step=1, value=1, description="q"),
    d=IntSlider(min=2, max=5, step=1, value=2, description="d"),
    breaker=Dropdown(options=["adversarial", "random"], value="adversarial",
                     description="Breaker"),
    seed=IntText(value=7, description="Seed"),
    verbose=Checkbox(value=False, description="Print trace"),
);

"""## 8. Play as Breaker (interactive)

You choose Breaker's edges; the algorithm plays Maker. Workflow per round:

1. Click **▶ Maker move** — the algorithm computes the next Maker edge (Phase 1, 2, or 3) and plays it.
2. Pick an edge from the dropdown and click **Claim**. Repeat $ times.
3. Go back to step 1 until either Maker closes a $ or Phase 2 finds no active dangerous edge.

Visual cues:
- Solid blue: Maker edges.
- Dashed red: Breaker edges (your picks; queued picks are also shown).
- Orange: ^*$ and the closer.
- Gold dotted: live threats {e^*} \setminus B$ (these are the edges you should try to block).
- Orange halo: the completed $.

Change $, $, $ in the cell below to experiment.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

class PlayAsBreaker:
    """Interactive game: user plays Breaker, the algorithm plays Maker."""

    def __init__(self, n=6, q=1, d=2):
        self.n, self.q, self.d = n, q, d
        self._reset_state()
        self._build_ui()

    def _reset_state(self):
        V = list(range(self.n))
        self.free = {edge(u, v) for u, v in combinations(V, 2)}
        self.M, self.B = set(), set()
        self.round = 0
        self.phase = "P1"
        self.e_star = None
        self.T_star = None
        self.cycle = None
        self.pending = []
        self.turn = "M"
        self.game_over = False
        self.message = (f"Click ▶ Maker move to start. You play Breaker (q = {self.q}).")

    def _next_maker_edge(self):
        """Algorithm picks Maker's next edge, advancing phase if needed."""
        if self.phase == "P1":
            cands = [e for e in self.free
                     if max(maker_degree(u, self.M) for u in e) < self.d]
            if cands:
                return min(cands, key=lambda e: sum(maker_degree(u, self.M) for u in e))
            self.phase = "P2"
        if self.phase == "P2":
            X = {v for v in range(self.n) if maker_degree(v, self.M) >= self.d}
            cands = sorted((e for e in self.free if all(u in X for u in e)),
                           key=lambda e: -len(threats(e, self.M) - self.B))
            for e in cands:
                T_e = threats(e, self.M)
                if len(T_e - self.B) > self.q:
                    self.e_star, self.T_star = e, T_e
                    self.phase = "P3"
                    return e
            return None  # No active dangerous edge
        if self.phase == "P3":
            survivors = self.T_star - self.B
            if survivors:
                return next(iter(survivors))
            return None
        return None

    def _do_maker(self, _=None):
        if self.game_over or self.turn != "M":
            return
        e = self._next_maker_edge()
        if e is None:
            if self.phase == "P2":
                self.message = "✗ No active dangerous edge — strategy fails. Breaker wins!"
            else:
                self.message = "✗ All threats blocked — Breaker wins!"
            self.game_over = True
            self._render()
            return
        self.round += 1
        self.free.discard(e)
        self.M.add(e)
        # Was this the cycle-closing edge?
        if self.phase == "P3" and self.e_star and e != self.e_star:
            a1, a2 = tuple(self.e_star)
            b1, b2 = tuple(e)
            if b1 in neighbours(a1, self.M) and b2 in neighbours(a2, self.M):
                self.cycle = [a1, b1, b2, a2]
            else:
                self.cycle = [a1, b2, b1, a2]
            cyc = " → ".join(map(str, self.cycle + [self.cycle[0]]))
            self.message = (f"✓ Round {self.round}: Maker plays {set(e)}. "
                            f"C_4 = {cyc}.  Maker wins!")
            self.game_over = True
        else:
            note = " (e*: high-degree edge with > q threats)" if self.phase == "P3" else ""
            self.message = (f"Round {self.round}: Maker plays {set(e)} "
                            f"({self.phase}{note}). Your turn — pick {self.q} edges.")
            self.turn = "B"
            self.pending = []
        self._render()

    def _do_breaker_claim(self, _=None):
        if self.game_over or self.turn != "B":
            return
        e = self.dropdown.value
        if e is None or e not in self.free or e in self.pending:
            return
        self.pending.append(e)
        if len(self.pending) >= self.q:
            for ed in self.pending:
                self.free.discard(ed)
                self.B.add(ed)
            picks = ", ".join(f"{{{min(p)},{max(p)}}}" for p in self.pending)
            self.message = f"Breaker claimed: {picks}. Click ▶ Maker move."
            self.pending = []
            self.turn = "M"
        else:
            self.message = (f"Pick {len(self.pending)}/{self.q} queued. "
                            "Pick another edge and Claim.")
        self._render()

    def _do_reset(self, _=None):
        self._reset_state()
        self._render()

    def _build_ui(self):
        self.btn_maker = widgets.Button(description="▶ Maker move",
                                        button_style="primary",
                                        layout=widgets.Layout(width="140px"))
        self.dropdown = widgets.Dropdown(description="Edge:",
                                         layout=widgets.Layout(width="220px"))
        self.btn_claim = widgets.Button(description="Claim",
                                        button_style="danger",
                                        layout=widgets.Layout(width="100px"))
        self.btn_reset = widgets.Button(description="↻ Reset",
                                        layout=widgets.Layout(width="100px"))
        self.btn_maker.on_click(self._do_maker)
        self.btn_claim.on_click(self._do_breaker_claim)
        self.btn_reset.on_click(self._do_reset)
        self.out_status = widgets.Output()
        self.out_plot = widgets.Output()
        self.ui = widgets.VBox([
            widgets.HBox([self.btn_maker, self.dropdown,
                          self.btn_claim, self.btn_reset]),
            self.out_status,
            self.out_plot,
        ])

    def _render(self):
        with self.out_status:
            clear_output(wait=True)
            print(self.message)
            line = (f"Phase: {self.phase}   |M|={len(self.M)}  "
                    f"|B|={len(self.B)}  free={len(self.free)}")
            if self.e_star is not None:
                line += (f"   e*={set(self.e_star)}  "
                         f"free threats: {len(self.T_star - self.B)}")
            print(line)

        # Refresh dropdown options
        usable = sorted(self.free - set(self.pending),
                        key=lambda e: tuple(sorted(e)))
        opts = [(f"({min(e)}, {max(e)})", e) for e in usable]
        cur = self.dropdown.value
        self.dropdown.options = opts
        if opts and cur not in [v for _, v in opts]:
            self.dropdown.value = opts[0][1]

        with self.out_plot:
            clear_output(wait=True)
            log = GameLog(n=self.n, d=self.d, q=self.q)
            log.M = self.M
            log.B = self.B | set(self.pending)
            log.e_star = self.e_star
            log.threats_e_star = self.T_star or set()
            log.cycle = self.cycle if self.game_over else None
            fig, ax = plt.subplots(figsize=(6.5, 6.5))
            draw_state(log, ax=ax,
                       show_threats=(self.e_star is not None
                                     and not self.game_over),
                       highlight_cycle=(self.cycle is not None),
                       highlight_e_star=(self.e_star is not None))
            plt.show()


def play_as_breaker(n=6, q=1, d=2):
    """Spawn an interactive game where you play Breaker."""
    g = PlayAsBreaker(n=n, q=q, d=d)
    g._render()
    display(g.ui)
    return g

# Try a smaller board first; later switch to n=10, q=3, d=3 for a real challenge.
g = play_as_breaker(n=6, q=1, d=2)