# -*- coding: utf-8 -*-
"""perfect_play_c3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_w0Lx9qlxVqBv6FjLV3gQahN4hY--ao9

# Pruned Perfect Play — Triangle ($K_3$) Game

Min–max search over the Maker–Breaker game tree with **memoisation** and **Erdős–Selfridge pruning**. Computes the exact threshold $q^{*}(n, K_3)$ for small $n$ and tracks the number of states explored.

**ES pruning rule.** At the start of Breaker's turn, if
$$ \Phi_{\mathrm{ES}}(M, B) \;=\; \sum_{\substack{A \in \mathcal{F} \\ A \cap B = \emptyset}} 2^{|A \cap M| - |A|} \;<\; 1, $$
then Breaker has a winning strategy (Erdős–Selfridge theorem) — we return immediately without recursing into the subtree.
"""

import math
import time
from itertools import combinations
import matplotlib.pyplot as plt
import numpy as np

IITR_BLUE   = "#1f497d"
IITR_ORANGE = "#df802a"
plt.rcParams["figure.dpi"] = 110

def edge(u, v):
    return frozenset({u, v})

def triangles(n):
    return [frozenset({edge(a, b), edge(b, c), edge(a, c)})
            for a, b, c in combinations(range(n), 3)]

"""## The search engine

Memoised min–max with optional ES pruning and move ordering by $|\Delta \Phi_{\mathrm{ES}}|$.
"""

class Game:
    """Perfect-play min–max for the Maker–Breaker game on K_n with winning family F."""

    def __init__(self, F, n, q, pruning=True, order=True):
        self.F = tuple(frozenset(A) for A in F)
        self.n = n
        self.q = q
        self.pruning = pruning
        self.order = order
        self.all_edges = frozenset(edge(u, v) for u, v in combinations(range(n), 2))
        self.cache = {}
        self.states_explored = 0

    def maker_won(self, M):
        return any(A <= M for A in self.F)

    def breaker_won(self, B):
        return all(A & B for A in self.F)

    def phi_es(self, M, B):
        s = 0.0
        for A in self.F:
            if A & B:
                continue
            s += 2 ** (len(A & M) - len(A))
        return s

    def order_moves(self, free, M, B, who):
        """Sort candidate edges by |ΔΦ_ES|, best first — improves cutoffs."""
        if not self.order:
            return list(free)
        base = self.phi_es(M, B)
        def delta(e):
            if who == "M":
                return self.phi_es(M | {e}, B) - base
            else:
                return base - self.phi_es(M, B | {e})
        return sorted(free, key=lambda e: -abs(delta(e)))

    def value(self, M, B, turn, b_left):
        key = (M, B, turn, b_left)
        if key in self.cache:
            return self.cache[key]
        self.states_explored += 1

        if self.maker_won(M):
            self.cache[key] = "M"; return "M"
        if self.breaker_won(B):
            self.cache[key] = "B"; return "B"

        free = self.all_edges - M - B
        if not free:
            self.cache[key] = "B"; return "B"

        if turn == "M":
            result = "B"
            for e in self.order_moves(free, M, B, "M"):
                new_M = M | {e}
                if self.maker_won(new_M):
                    result = "M"; break
                next_turn, next_left = ("M", 0) if self.q == 0 else ("B", self.q)
                if self.value(new_M, B, next_turn, next_left) == "M":
                    result = "M"; break
        else:
            # ES pruning at start of Breaker's turn
            if self.pruning and b_left == self.q:
                if self.phi_es(M, B) < 1:
                    self.cache[key] = "B"; return "B"
            result = "M"
            for e in self.order_moves(free, M, B, "B"):
                new_B = B | {e}
                if self.breaker_won(new_B):
                    sub = "B"
                elif b_left == 1:
                    sub = self.value(M, new_B, "M", self.q)
                else:
                    sub = self.value(M, new_B, "B", b_left - 1)
                if sub == "B":
                    result = "B"; break

        self.cache[key] = result
        return result

    def play(self):
        return self.value(frozenset(), frozenset(), "M", self.q)


def threshold(F, n, pruning=True, order=True, q_max=None, time_limit=300):
    """Smallest q where Breaker wins. Also returns states explored at q*-1 and q*."""
    if q_max is None:
        q_max = math.comb(n, 2)
    states = {}
    timings = {}
    last_maker = None
    for q in range(1, q_max + 1):
        t0 = time.time()
        g = Game(F, n, q, pruning=pruning, order=order)
        winner = g.play()
        dt = time.time() - t0
        states[q] = g.states_explored
        timings[q] = dt
        if dt > time_limit:
            return None, states, timings
        if winner == "M":
            last_maker = q
        else:
            return q, states, timings
    return q_max + 1, states, timings

"""## Sanity check: a single game"""

F = triangles(5)
for q in range(1, 5):
    g = Game(F, 5, q, pruning=True)
    winner = g.play()
    print(f"n=5, q={q}: winner = {winner}, states explored = {g.states_explored}")

"""## Exact thresholds $q^{*}(n, K_3)$ for $n = 3 \ldots 6$

We sweep $q$ upward and find the smallest value at which Breaker wins.
"""

ns = [3, 4, 5, 6]      # set to [3, 4, 5, 6, 7] if you have time
exact = {}
states_at_threshold = {}
states_pruned = {}
states_plain  = {}

for n in ns:
    F = triangles(n)
    q_star, states_p, _ = threshold(F, n, pruning=True, order=True)
    exact[n] = q_star
    states_pruned[n] = states_p
    if n <= 5:
        _, states_pl, _ = threshold(F, n, pruning=False, order=False, q_max=q_star)
        states_plain[n] = states_pl
    else:
        states_plain[n] = None  # skip plain at larger n
    print(f"n={n}: q*(n, K_3) = {q_star}")

# Build a summary table: states explored at q just-below threshold (Maker's hardest game)
rows = []
for n in ns:
    q_play = max(0, exact[n] - 1)
    pruned = states_pruned[n].get(q_play, "--")
    plain = states_plain[n].get(q_play, "--") if states_plain[n] is not None else "--"
    speedup = (f"{plain / pruned:.0f}×"
               if isinstance(plain, int) and isinstance(pruned, int) and pruned > 0
               else "--")
    rows.append((n, exact[n], q_play, plain, pruned, speedup))

print(f"{'n':>3} {'q*':>4} {'q played':>9} {'plain':>14} {'pruned':>14} {'speedup':>10}")
print("-" * 60)
for r in rows:
    n, qs, qp, pl, pr, sp = r
    pl_s = f"{pl:.2e}" if isinstance(pl, int) else str(pl)
    pr_s = f"{pr:.2e}" if isinstance(pr, int) else str(pr)
    print(f"{n:>3} {qs:>4} {qp:>9} {pl_s:>14} {pr_s:>14} {sp:>10}")

# Plot states explored (log scale)
fig, ax = plt.subplots(figsize=(8, 5))
qs_plain = [r[3] for r in rows if isinstance(r[3], int)]
ns_plain = [r[0] for r in rows if isinstance(r[3], int)]
ax.semilogy(ns_plain, qs_plain, "o--", color="red",
            label="Plain (no pruning)", linewidth=2, markersize=8)
ax.semilogy([r[0] for r in rows], [r[4] for r in rows], "o-",
            color=IITR_BLUE, label="ES-pruned", linewidth=2, markersize=8)
ax.set_xlabel("n"); ax.set_ylabel("States explored")
ax.set_title("Effect of ES pruning on search tree size — triangle game",
             color=IITR_BLUE)
ax.grid(True, alpha=0.3, which="both")
ax.legend(); plt.tight_layout(); plt.show()

"""## Threshold vs analytic bounds

$$ \sqrt{2n} - O(1) \;\leq\; q^{*}(n, K_3) \;\leq\; (2 - 1/24)\sqrt{n}. $$
"""

ns_arr = np.array(list(exact.keys()))
qs_arr = np.array([exact[n] for n in ns_arr])

fig, ax = plt.subplots(figsize=(8, 5))
x = np.linspace(min(ns_arr) - 0.5, max(ns_arr) + 0.5, 200)
ax.plot(x, np.sqrt(2 * x), "--", color="grey",
        label=r"BL lower $\sqrt{2n}$")
ax.plot(x, (2 - 1/24) * np.sqrt(x), "--", color="purple",
        label=r"GS upper $(2 - 1/24)\sqrt{n}$")
ax.plot(ns_arr, qs_arr, "o-", color=IITR_BLUE, linewidth=2.5,
        markersize=10, label=r"Exact $q^{*}(n, K_3)$")
ax.set_xlabel("n"); ax.set_ylabel("q")
ax.set_title("Exact triangle threshold vs analytic bounds",
             color=IITR_BLUE)
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""## Notes

- The plain (no-pruning) search becomes infeasible quickly: for $n=6$ the state space $3^{\binom{6}{2}} = 3^{15} \approx 1.4 \cdot 10^{7}$ is already large; for $n=7$ it is $\sim 10^{10}$.
- ES pruning cuts the explored set by 1–2 orders of magnitude in the regime where both versions complete.
- To extend to $n=7, 8$, set `ns = [3, 4, 5, 6, 7, 8]` above and wait several minutes — only the pruned variant will finish in reasonable time.
- Move ordering by $|\Delta \Phi_{ES}|$ gives an additional constant-factor speedup; toggle with `order=True/False`.

## Note on the threshold convention

The values computed above use the definition from the Sowa–Srivastav and Bednarska–Łuczak literature:

$$ q^*(n, K_3) \;=\; \min\{\,q \in \mathbb{N}_0 :\ \text{Breaker wins the $(1{:}q)$-game}\,\}. $$

Under this definition, computing exact values for small $n$ gives:

| $n$ | 3 | 4 | 5 | 6 |
|---|---|---|---|---|
| $q^{*}(n,K_3)$ | 1 | 1 | 2 | 2 |

Some references tabulate $q^*$ shifted by $+1$ — i.e., they report the *largest* $q$ at which Maker still wins, plus one. Be careful when comparing with secondary sources. The values produced by this notebook are the strict $\min$-form thresholds as defined above.
"""